import type { BreakpointLayouts, CommandCenterWidgetId, LayoutItem, WorkspaceLayoutState } from "./types";

export const LAYOUT_STORAGE_KEY = "lifeos-workspace-os-v1-layout";
export const LAST_WORKSPACE_KEY = "lifeos-workspace-os-v1-last-workspace";

const WIDGET_IDS: CommandCenterWidgetId[] = [
  "mission-status",
  "cognitive-support",
  "project-command-board",
  "decision-queue",
  "morning-brief",
  "personal-growth",
  "github-health",
  "revenue-radar",
  "prayer",
  "ai-workforce",
];

function item(
  id: CommandCenterWidgetId,
  x: number,
  y: number,
  w: number,
  h: number,
  minW = 3,
  minH = 3,
): LayoutItem {
  return { i: id, x, y, w, h, minW, minH };
}

/** Desktop-first default. Smaller breakpoints are generated by stacking. */
export const DEFAULT_LG_LAYOUT: LayoutItem[] = [
  item("mission-status", 0, 0, 12, 3, 6, 3),
  item("cognitive-support", 0, 3, 12, 8, 6, 5),
  item("project-command-board", 0, 11, 8, 10, 6, 6),
  item("decision-queue", 8, 11, 4, 10, 3, 5),
  item("morning-brief", 0, 21, 6, 7, 4, 5),
  item("personal-growth", 6, 21, 6, 7, 4, 5),
  item("github-health", 0, 28, 4, 6, 3, 4),
  item("revenue-radar", 4, 28, 4, 6, 3, 4),
  item("prayer", 8, 28, 4, 6, 3, 4),
  item("ai-workforce", 0, 34, 12, 7, 6, 5),
];

function stackLayout(source: LayoutItem[], cols: number): LayoutItem[] {
  let y = 0;
  return source.map((entry) => {
    const w = Math.min(cols, Math.max(entry.minW ?? 1, entry.w > cols ? cols : entry.w));
    const next = { ...entry, x: 0, y, w, h: entry.h };
    y += entry.h;
    return next;
  });
}

/** Scale a 12-col layout into fewer columns while preserving relative placement. */
function scaleLayout(source: LayoutItem[], cols: number): LayoutItem[] {
  const scale = cols / 12;
  return source.map((entry) => {
    const minW = Math.min(cols, entry.minW ?? 1);
    const w = Math.min(cols, Math.max(minW, Math.round(entry.w * scale)));
    const x = Math.min(cols - w, Math.max(0, Math.round(entry.x * scale)));
    return { ...entry, x, w, minW, minH: entry.minH };
  });
}

export function createDefaultLayouts(): BreakpointLayouts {
  return {
    lg: DEFAULT_LG_LAYOUT.map((entry) => ({ ...entry })),
    // Desktop content width is often <1200px once the sidebar is present, so md
    // must remain a real multi-column board (not a stacked list).
    md: scaleLayout(DEFAULT_LG_LAYOUT, 10),
    sm: scaleLayout(DEFAULT_LG_LAYOUT, 6),
    xs: stackLayout(DEFAULT_LG_LAYOUT, 4),
  };
}

export function createDefaultWidgetChrome(): Record<string, { minimized: boolean; hidden: boolean }> {
  return Object.fromEntries(WIDGET_IDS.map((id) => [id, { minimized: false, hidden: false }]));
}

export const WORKSPACE_LAYOUT_VERSION = 2 as const;

export function createDefaultWorkspaceLayout(): WorkspaceLayoutState {
  return {
    version: WORKSPACE_LAYOUT_VERSION,
    workspaceId: "command-center",
    layouts: createDefaultLayouts(),
    widgets: createDefaultWidgetChrome(),
    focusedWidgetId: null,
    reducedMotion: false,
  };
}

export const COMMAND_CENTER_WIDGET_META: Record<
  CommandCenterWidgetId,
  { title: string; eyebrow: string; primaryAction: string }
> = {
  "mission-status": {
    title: "Mission status",
    eyebrow: "Live vault signals",
    primaryAction: "Review blocked work",
  },
  "cognitive-support": {
    title: "Cognitive support",
    eyebrow: "Low-load focus",
    primaryAction: "Focus current step",
  },
  "project-command-board": {
    title: "Project command board",
    eyebrow: "Execution control",
    primaryAction: "Stage a change",
  },
  "decision-queue": {
    title: "Decision queue",
    eyebrow: "Next commitments",
    primaryAction: "Open top priority",
  },
  "morning-brief": {
    title: "Morning brief",
    eyebrow: "Attention",
    primaryAction: "Open first priority",
  },
  "personal-growth": {
    title: "Personal growth",
    eyebrow: "Steady progress",
    primaryAction: "Review growth focus",
  },
  "github-health": {
    title: "GitHub health",
    eyebrow: "Delivery signal",
    primaryAction: "Inspect repository health",
  },
  "revenue-radar": {
    title: "Revenue radar",
    eyebrow: "Business signal",
    primaryAction: "Review revenue state",
  },
  prayer: {
    title: "Prayer",
    eyebrow: "Anchored focus",
    primaryAction: "Read reflection",
  },
  "ai-workforce": {
    title: "AI workforce",
    eyebrow: "Accountable automation",
    primaryAction: "Review agents",
  },
};

export { WIDGET_IDS as COMMAND_CENTER_WIDGET_IDS };
